name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DOCS_CHECKOUT_PAT }}

      - run: |
          sudo apt install doxygen
          cd docs
          doxygen

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DOCS_CHECKOUT_PAT }}
          publish_dir: docs/html

